<?php

declare(strict_types=1);

namespace CoolMS\Core\Mapping;

use Attribute;

/**
 * How the identifier is produced.
 *
 * `$generator` is a LOGICAL name, resolved by the persistence adapter to
 * whatever that library calls the same thing -- the same contract as
 * {@see Column::$type}. It deliberately is not a class name: a class name is a
 * dependency wearing a string, and a second adapter would have to recognise the
 * first one's classes to honour it.
 *
 * Adding a generator means adding a constant here and an entry in each adapter.
 * An adapter that meets a name it does not know must fail, not guess -- a
 * silently unmapped identifier is a broken schema.
 */
#[Attribute(Attribute::TARGET_PROPERTY)]
final readonly class GeneratedValue
{
    public const string AUTO = 'AUTO';

    public const string NONE = 'NONE';

    public const string CUSTOM = 'CUSTOM';

    /** Time-ordered UUID, generated by the application rather than the database. */
    public const string UUID_V7 = 'uuid_v7';

    public function __construct(
        public string $strategy = self::AUTO,
        public ?string $generator = null,
    ) {
    }
}
